/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./.storybook/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--color-primary)',
          dark: 'var(--color-primary-dark)',
          light: 'var(--color-primary-light)',
          lighter: 'var(--color-primary-lighter)',
          lightest: 'var(--color-primary-lightest)',
        },
        secondary: {
          DEFAULT: 'var(--color-secondary)',
          dark: 'var(--color-secondary-dark)',
          darker: 'var(--color-secondary-darker)',
          darkest: 'var(--color-secondary-darkest)',
        },
        tertiary: {
          DEFAULT: 'var(--color-tertiary)',
          dark: 'var(--color-tertiary-dark)',
          light: 'var(--color-tertiary-light)',
        },
        error: {
          DEFAULT: 'var(--color-error)',
          dark: 'var(--color-error-dark)',
          light: 'var(--color-error-light)',
        },
        success: {
          DEFAULT: 'var(--color-success)',
          dark: 'var(--color-success-dark)',
          light: 'var(--color-success-light)',
        },
        warning: {
          DEFAULT: 'var(--color-warning)',
          dark: 'var(--color-warning-dark)',
          light: 'var(--color-warning-light)',
        },
        neutral: {
          black: 'var(--color-neutral-black)',
          white: 'var(--color-neutral-white)',
          DEFAULT: 'var(--color-neutral-default)',
          dark: 'var(--color-neutral-dark)',
          light: 'var(--color-neutral-light)',
          'black-10': 'var(--color-neutral-black-10)',
          'black-30': 'var(--color-neutral-black-30)',
          'black-40': 'var(--color-neutral-black-40)',
          'white-30': 'var(--color-neutral-white-30)',
        },
        surface: {
          page: 'var(--color-surface-page)',
          hover: 'var(--color-surface-hover)',
          'action-primary': 'var(--color-surface-action-primary)',
          'action-secondary': 'var(--color-surface-action-secondary)',
          'action-hover-primary': 'var(--color-surface-action-hover-primary)',
          'action-hover-secondary': 'var(--color-surface-action-hover-secondary)',
          'disabled-light': 'var(--color-surface-disabled-light)',
          'disabled-dark': 'var(--color-surface-disabled-dark)',
          secondary: 'var(--color-surface-secondary)',
          'brand-primary': 'var(--color-surface-brand-primary)',
          'brand-secondary': 'var(--color-surface-brand-secondary)',
        },
        text: {
          headings: 'var(--color-text-headings)',
          body: 'var(--color-text-body)',
          disabled: 'var(--color-text-disabled)',
          error: 'var(--color-text-error)',
          'action-active': 'var(--color-text-action-active)',
          'action-on-primary': 'var(--color-text-action-on-primary)',
          'action-on-secondary': 'var(--color-text-action-on-secondary)',
          'action-on-tertiary': 'var(--color-text-action-on-tertiary)',
          brand: 'var(--color-text-brand)',
          passive: 'var(--color-text-passive)',
          'action-inverse': 'var(--color-text-action-inverse)',
          'action-disabled': 'var(--color-text-action-disabled)',
          warning: 'var(--color-text-warning)',
        },
        border: {
          primary: 'var(--color-border-primary)',
          disabled: 'var(--color-border-disabled)',
          error: 'var(--color-border-error)',
          'action-active': 'var(--color-border-action-active)',
          passive: 'var(--color-border-passive)',
        },
        icon: {
          'action-active': 'var(--color-icon-action-active)',
          'action-on-primary': 'var(--color-icon-action-on-primary)',
          'action-on-secondary': 'var(--color-icon-action-on-secondary)',
          'action-inverse': 'var(--color-icon-action-inverse)',
          'action-disabled': 'var(--color-icon-action-disabled)',
          error: 'var(--color-icon-error)',
          positive: 'var(--color-icon-positive)',
        },
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        round: 'var(--radius-round)',
      },
      spacing: {
        xs: 'var(--spacing-xs)',
        sm: 'var(--spacing-sm)',
        md: 'var(--spacing-md)',
        lg: 'var(--spacing-lg)',
        xl: 'var(--spacing-xl)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
